// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiMpky9QgNuJwOEDbcsEi7xY5hNkga0vY',
    appId: '1:519422718017:android:2edc1dad916bd2042756c0',
    messagingSenderId: '519422718017',
    projectId: 'evently-d3561',
    databaseURL: 'https://evently-d3561-default-rtdb.firebaseio.com',
    storageBucket: 'evently-d3561.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW8NZx7SXucUqmyXbRDO9f0kB6is3ctPw',
    appId: '1:519422718017:ios:55b8c5039598afda2756c0',
    messagingSenderId: '519422718017',
    projectId: 'evently-d3561',
    databaseURL: 'https://evently-d3561-default-rtdb.firebaseio.com',
    storageBucket: 'evently-d3561.firebasestorage.app',
    androidClientId: '519422718017-1p46nsq6p46q7jdjpam6n04u31bv3mp7.apps.googleusercontent.com',
    iosClientId: '519422718017-1uiprhc0btk8bsphed0d7dpijt5prmr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.evently',
  );

}